[development]
address = "0.0.0.0"
port = 8002
workers = 4
log = "normal"

[staging]
address = "0.0.0.0"
port = 8003
workers = 4
log = "normal"

[production]
address = "0.0.0.0"
port = 8004
workers = 4
log = "critical"